### ISSUE TITLE
Gold path reports incorrect upgrade

### ISSUE THREAD

**Issue by starphoenix** [colblitz/YATTO#10]
With my current state string I have a "Future's Fortune" at level 45.  When I enter 1 step to calculate and look at the gold path it tells me I need to upgrade it to 53 as a single step.

24.52,25.100,6.25,26.110,21.10,1.110,3.147,5.146,13.164,23.25,12.10,9.140,19.90,16.10,22.10,0.45,18.110,10.45,2.10,28.5,11.140,15.110,7.25,17.10,14.10,4.112,20.25,8.90,27.10|6600.3,6600.3,6600.3,6600.1,6600.0,6500.2,6500.2,6500.4,6500.1,6400.2,6400.8,6400.2,6300.2,6300.2,6300.4,6200.2,6200.3,6200.6,6100.3,6100.3,6000.4,5900.4,5900.8,5800.3,5700.4,5500.0,5200.3,4700.2,4100.4,3600.3,3000.2,2400.0,1760.4|0.7,0.47,0.38,0.92,0.045,0.2|1,1,1,1,0,0|1870|1|1|5|2745|100|187460

**Comment by colblitz** [comment]
That's by design - the multiplier that FF is involved in is rounded up (in calculate.js, line 532, and in the AEC by bsedmonds you'd see that it also uses a ROUNDUP), and so most upgrades don't actually have any effect except at certain levels when the multiplier ticks up. Given this the current way of dealing with this step-ness is to treat the entire upgrade up to the next breakpoint as one step, and so effectively average the gold gain against the cost of upgrading multiple levels. This isn't necessarily the most "correct" way of handling it (/u/contigi has mentioned coming up with a different way of dealing with it), but for now this is intended
